Added fetching results from server

diff --git a/dev/server_scripts/server_update b/dev/server_scripts/server_update
--- a/dev/server_scripts/server_update
+++ b/dev/server_scripts/server_update
@@ -20,7 +20,7 @@ function rest_command {
   #
   # Submit a json paket to the server
 
-  API_URL="172.19.211.159:8000/jobs/api"
+  API_URL="172.19.211.159:80/jobs/api"
   JSON="${1}"
   JOB_PK=${2}
   TOKEN="${3:-}"
@@ -67,17 +67,33 @@ function update_status {
     echo "    Update the stats of the job"
     echo "    Usage: status job_id state desc token"
     echo "       job_id     the server assigned job id"
-    echo "       state      state intiger to update the job to"
+    echo "       state      job state (WARN, OK, FAILED)"
     echo "       desc       description explaining why the state was updated"
     echo "       token      authentication token provided by the webserver"
     exit 1
   fi
 
   JOB_PK=${2}
-  STATE="${3}"
+  STATE_STR="${3}"
   DESC="${4}"
   TOKEN="${5:-}"
   DATE_TIME=$(date +%Y-%m-%dT%H:%M:%S)
+
+  case $STATE_STR in
+    "OK")
+        STATE=3
+        ;;
+    "WARN")
+        STATE=4
+        ;;
+    "FAILED")
+        STATE=2
+        ;;
+    *)
+        echo "ERROR: job state not one of WARN, OK, FAILED"
+        exit 1
+  esac
+  
   JSON="{
       \"submission_id\": \"\",
       \"task_set\": [],
